<%@ Page Language="C#" AutoEventWireup="true" CodeFile="LogIn.aspx.cs" Inherits="LogIn" %>

<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"  /><title><%= Constant.Title %></title><link href="css/fonts.css" rel="stylesheet" type="text/css" /><link href="css/style.css" rel="stylesheet" type="text/css" /><script src="js/jquery-1.8.2.min.js"></script><script type="text/javascript" src="js/html5.js"></script><link href="css/media.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/Login.js"></script><script type="text/javascript" src="js/jquery.placeholder.js"></script><script type="text/javascript" src="js/jquery.placeholder.min.js"></script><link rel="shortcut icon" type="image/x-icon" href="images/JayChem.jpg" /><link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'/><script type="text/javascript">    $(document).ready(function () {
        $("#tb_Password").keyup(function (event) {
            if (event.keyCode == 13) {
                $("#btn_Login").click();
            }
        });
    });</script><script type="text/javascript">    function checkDec(el) {
        var ex = /^[0-9]+\.?[0-9]*$/;        if (ex.test(el.value) == false) {
            el.value = el.value.substring(0, el.value.length - 1);
        }
    }</script></head><body style="position:relative;" class="login-bg"><form runat="server" id="frm_login" style="overflow:hidden;">  <main>    <div class="login">      <div class="l_part_top">        <div class="l_part_wrap">          <div class="logo">            <div class="text_middle"> <img src="images/jay-logo.png" alt="Jay Chemicals"> </div>          </div>        </div>      </div>      <div class="l_part_last">        <div class="l_part_wrap">          <div class="login_form">            <div class="field_part">              <%--<input type="text" class="u_field" placeholder="User Id" />--%>              <asp:TextBox runat="server" ID="tb_UserId" CssClass="u_field" ></asp:TextBox>            </div>            <div class="field_part">              <%--<input type="text" class="u_field" placeholder="Enter Pin No." />--%>              <asp:TextBox runat="server" ID="tb_Password"   CssClass="u_field" TextMode="Password"  onkeydown = "return (event.keyCode!=13);" onkeyup="checkDec(this);" ></asp:TextBox>            </div>            <div class="field_part"><%--<input type="button" id="btn_Login" value="Login" class="u_button" onclick="window.location.href = 'dashboard.html'" name="" />--%>              <input type="button" id="btn_Login"  value="Login" class="u_button" onclick="return CheckLogIn();" />              <%--<asp:Button runat="server" ID="btn_Login" Text="Login" CssClass="u_button" OnClientClick="return CheckLogIn();" />--%>              </div>              <div class="field_part">              <div class="forgot_part" style="padding-bottom:20px;"> <a href="ForgotPassword.aspx" class="link20_wht">Change/Forgot PIN?</a> </div>            </div>          </div>        </div>      </div>    </div>    <!--<footer><div class="copyright">© 2016 Jay Chemical Industries Ltd.</div></footer>-->  </main></form></body></html>